networks:
  stack:
    name: stack
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16



services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      sh -c 'redis-server
      --save 20 1
      --loglevel warning
      --requirepass "$$REDIS_PASSWORD"'
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    networks:
      - stack

  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - stack
