networks:
  stack:
    name: ${ATI_NETWORK_NAME:-stack}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ATI_NETWORK_SUBNET:-172.21.0.0/16}



services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      sh -c 'redis-server
      --save 20 1
      --loglevel warning
      --requirepass "$$REDIS_PASSWORD"'
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      stack:
        ipv4_address: ${ATI_NETWORK_PREFIX:-172.21.0}.30

  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      stack:
        ipv4_address: ${ATI_NETWORK_PREFIX:-172.21.0}.31

  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    profiles:
      - ib
    container_name: ib-gateway
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - TWS_USERID=${TWS_USERID}
      - TWS_PASSWORD=${TWS_PASSWORD}
      - TRADING_MODE=paper
      - TWS_SETTINGS_PATH=/home/ibgateway/tws_settings
      - READ_ONLY_API=no
      - API_PORT=4004
      - VNC_SERVER_PASSWORD=${VNC_SERVER_PASSWORD}
      - TWOFA_TIMEOUT_ACTION=restart
      - RELOGIN_AFTER_TWOFA_TIMEOUT=yes
      - ALLOW_BLIND_TRADING=no
    volumes:
      - ./data/ib-gateway/tws_settings:/home/ibgateway/tws_settings
    networks:
      stack:
        ipv4_address: ${ATI_NETWORK_PREFIX:-172.21.0}.32

volumes:
  redis-data:
  mariadb-data:
